### ISSUE TITLE
Bad value for FM damage calculation

### ISSUE THREAD

**Issue by BanosAyado** [dlebansais/PgBuilder-Disclosed#2]
The calculation of the damage for Fire Magic is wrong somewhere. I have +24% direct fire damage from Tailoring on both my chest and pants, though the value given for fireball is the same as the game.

* With Pants/Shirt: 484
* Shirt Only: 458
* Pants Only: 387
* Without Pants/Shirt: 364

As for the rest, I will put the screenshot of my skills with Shirt and Pants and without them.

![Without Shirt   Pants](https://user-images.githubusercontent.com/65296569/82048090-42f73b80-96b4-11ea-8152-04f161b6f396.jpg)
![Without Shirt](https://user-images.githubusercontent.com/65296569/82048094-438fd200-96b4-11ea-8809-6a5b7325ef30.jpg)
![Full](https://user-images.githubusercontent.com/65296569/82048095-438fd200-96b4-11ea-863f-d4f4f4a5d0d4.jpg)
![Without Pants](https://user-images.githubusercontent.com/65296569/82048096-44286880-96b4-11ea-9d2c-4c6893c9fbbf.jpg)

**Comment by BanosAyado** [comment]
[test fmim.txt](https://github.com/dlebansais/PgBuilder-Disclosed/files/4634705/test.fmim.txt)

Forgot to add my build.

**Comment by dlebansais** [comment]
A vérifier dans la dernière version (v1.0.0.265). Spécialement Frostball.
