### ISSUE TITLE
Save function overwriting currently loaded build

### ISSUE THREAD

**Issue by AndyGneiss** [dlebansais/PgBuilder-Disclosed#5]
The "Save..." function is overwriting the currently loaded build file, even when using a new name for the new save file.

**Comment by AndyGneiss** [comment]
An update for clarification, as the problem isn't exactly what I originally wrote (sorry, should have tested this first but there's still an issue).
The build list in the program appears to load the same, newly saved build file for the newly listed entry and the previous build list entry. 

Example / steps to recreate: 
Load a build so that it is at the bottom of the list. Modify it & save it as a new build with a new name. If the problem is successfully recreated, you'll see the last two build list entries and clicking between the two will show the same build. This does not appear to overwrite the actual .txt file for the older build.

**Comment by dlebansais** [comment]
Thanks for the report. I apologize for being late to catch up, but I was waiting for the next patch (and it's been a long wait).
The behavior of the button is sort of intended, it's the label that is misleading. I have changed it to "Copy". Hopefully people can better understand the intent.
The new version is online. I plan to close this issue shortly.
