### ISSUE TITLE
Archery Fire Mod and BC Golem Damage Boosts

### ISSUE THREAD

**Issue by jacorobe** [dlebansais/PgBuilder-Disclosed#7]
The Archery mod "Direct Fire Damage +100 and Indirect Fire +13 (per tick) while Archery skill active" boosts all Archery abilities, even those that aren't fire damage.

The BC golem damage boosts are also listed as +25% and +X damage to X attack, but in the game, all damage boosts are +15% and +X damage to X attack. The second part seems good, just the percentage boost.

**Comment by dlebansais** [comment]
I see it even with the latest client (to be released). I'll try to fix it ASAP. Thanks for the report.

**Comment by dlebansais** [comment]
It should be fixed with the new release, though in doing so I probably bugged something else. Time will tell.
