### ISSUE TITLE
Lunge mods and Ice Armor Suggestion

### ISSUE THREAD

**Issue by jacorobe** [dlebansais/PgBuilder-Disclosed#8]
It seems the Lunge mods "Lunge deals +X% damage to health and armor" and "Lunge hits all enemies within 7 meters and deals +X damage to health and armor, but reuse timer is +2 seconds" aren't contributing to the Lunge damage calculation properly. Adding and removing either mod doesn't alter the displayed values. The 'Strategic Thrust and Lunge' mod works as intended.

Ice Armor currently doesn't display additional physical/cold mitigation from mods unlike Blocking Stance when additional mitigation mods are included. It doesn't seem to add this in the "Other Effects:" section either.

Much appreciated for the work you put into this project!

**Comment by dlebansais** [comment]
Thanks for the report. Fixes will be in the next release.
